// resources/js/Pages/Auth/Register.tsx
import { FormEvent } from 'react';
import { Head, Link, useForm } from '@inertiajs/react';

export default function Register() {
    const { data, setData, post, processing, errors, reset } = useForm({
        name: '',
        email: '',
        password: '',
        password_confirmation: '',
    });

    const handleSubmit = (e: FormEvent) => {
        e.preventDefault();
        post('/register', {
            onFinish: () => reset('password', 'password_confirmation'),
        });
    };

    return (
        <div className="min-h-screen flex items-center justify-center bg-gray-50">
            <Head title="Register" />
            <div className="card w-full max-w-md">
                <h1 className="text-2xl font-bold text-center mb-6">Create Account</h1>
                <form onSubmit={handleSubmit} className="space-y-4">
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">Name</label>
                        <input type="text" className="input" value={data.name}
                            onChange={(e) => setData('name', e.target.value)} required />
                        {errors.name && <p className="text-red-500 text-sm mt-1">{errors.name}</p>}
                    </div>
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">Email</label>
                        <input type="email" className="input" value={data.email}
                            onChange={(e) => setData('email', e.target.value)} required />
                        {errors.email && <p className="text-red-500 text-sm mt-1">{errors.email}</p>}
                    </div>
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">Password</label>
                        <input type="password" className="input" value={data.password}
                            onChange={(e) => setData('password', e.target.value)} required />
                        {errors.password && <p className="text-red-500 text-sm mt-1">{errors.password}</p>}
                    </div>
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">Confirm Password</label>
                        <input type="password" className="input" value={data.password_confirmation}
                            onChange={(e) => setData('password_confirmation', e.target.value)} required />
                    </div>
                    <button type="submit" disabled={processing} className="btn-primary w-full">
                        {processing ? 'Creating...' : 'Register'}
                    </button>
                </form>
                <p className="text-center mt-4 text-sm text-gray-600">
                    Already have an account?{' '}
                    <Link href="/login" className="text-ml-primary-600 hover:underline">Sign In</Link>
                </p>
            </div>
        </div>
    );
}

// resources/js/Pages/Auth/Register.vue
<script setup lang="ts">
import { Head, Link, useForm } from '@inertiajs/vue3';
import { FormEvent } from 'vue';

const form = useForm({
    name: '',
    email: '',
    password: '',
    password_confirmation: '',
});

const submit = (e: FormEvent) => {
    e.preventDefault();
    form.post('/register', {
        onFinish: () => form.reset('password', 'password_confirmation'),
    });
};
</script>

<template>
    <div class="min-h-screen flex items-center justify-center bg-gray-50">
        <Head title="Register" />
        <div class="card w-full max-w-md">
            <h1 class="text-2xl font-bold text-center mb-6">Create Account</h1>
            <form @submit="submit" class="space-y-4">
                <div>
                    <label class="block text-sm font-medium text-gray-700 mb-1">Name</label>
                    <input type="text" class="input" v-model="form.name" required />
                    <p v-if="form.errors.name" class="text-red-500 text-sm mt-1">{{ form.errors.name }}</p>
                </div>
                <div>
                    <label class="block text-sm font-medium text-gray-700 mb-1">Email</label>
                    <input type="email" class="input" v-model="form.email" required />
                    <p v-if="form.errors.email" class="text-red-500 text-sm mt-1">{{ form.errors.email }}</p>
                </div>
                <div>
                    <label class="block text-sm font-medium text-gray-700 mb-1">Password</label>
                    <input type="password" class="input" v-model="form.password" required />
                    <p v-if="form.errors.password" class="text-red-500 text-sm mt-1">{{ form.errors.password }}</p>
                </div>
                <div>
                    <label class="block text-sm font-medium text-gray-700 mb-1">Confirm Password</label>
                    <input type="password" class="input" v-model="form.password_confirmation" required />
                </div>
                <button type="submit" :disabled="form.processing" class="btn-primary w-full">
                    {{ form.processing ? 'Creating...' : 'Register' }}
                </button>
            </form>
            <p class="text-center mt-4 text-sm text-gray-600">
                Already have an account?
                <Link href="/login" class="text-ml-primary-600 hover:underline">Sign In</Link>
            </p>
        </div>
    </div>
</template>
